name: Build Psych Online + Release
run-name: Psych Online 0.13.2 Mobile (Port) + Pc
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: PsychOnline

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Android
            os: macos-15
            buildArgs: "android -final -D officialBuild"
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -final -nosign -D officialBuild"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
          - name: Windows x64
            os: windows-2022
            buildArgs: "windows -final -X64 -D HXCPP_X64 -D 64bits"
            artifactName: Windows x64
            artifactPath: export/release/windows/64bits/bin/*
          - name: Windows x32
            os: windows-2022
            buildArgs: "windows -final -X32 -D HXCPP_X32 -D 32bits"
            artifactName: Windows x32
            artifactPath: export/release/windows/32bits/bin/*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: "linux -final"
            artifactName: Linux
            artifactPath: export/release/linux/bin/*
          - name: MacOS
            os: macos-15
            buildArgs: "mac -final"
            artifactName: MacOS
            artifactPath: export/release/macos/bin/*
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        assetType: ${{ matrix.assetType }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: androidBuild
          path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: iOSBuild
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS.ipa

      - name: Download Windows x64 Build
        uses: actions/download-artifact@main
        with:
          name: Windows x64
          path: /home/runner/Windows-x64

      - name: Zip Windows x64 Build For Release
        run: |
          cd /home/runner/Windows-x64
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x64.zip" .

      - name: Download Windows x32 Build
        uses: actions/download-artifact@main
        with:
          name: Windows x32
          path: /home/runner/Windows-x32

      - name: Zip Windows x32 Build For Release
        run: |
          cd /home/runner/Windows-x32
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-x32.zip" .

      - name: Download Linux Build
        uses: actions/download-artifact@main
        with:
          name: Linux
          path: /home/runner/Linux

      - name: Tar Linux Build For Release
        run: |
          cd /home/runner/Linux
          tar czf "/home/runner/${{ env.PROJECT_NAME }}-Linux.tar" .

      - name: Download MacOS Build
        uses: actions/download-artifact@main
        with:
          name: MacOS
          path: /home/runner/MacOS

      - name: Tar MacOS Build For Release
        run: |
          cd /home/runner/MacOS
          tar czf "/home/runner/${{ env.PROJECT_NAME }}-MacOS.tar" .

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "PsychOnline 0.13.2 Mobile Bugfix"
          tag_name: "0.13.2-bugfix-mobile"
          prerelease: false
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
            /home/runner/*.tar
            /home/runner/*.zip
